#!/bin/sh
set -e
set -o noglob
########################################################################
### 生成离线镜像包
# $ curl -sfL https://renlm.github.io/sh/docker-save-images.sh | PLATFORM=linux/amd64 sh -s - -i registry:3.1.1 -o registry-3.1.1
# $ curl -sfL https://renlm.github.io/sh/docker-save-images.sh | PLATFORM=linux/arm64 sh -s - -i registry:3.1.1 -o registry-3.1.1
# $ curl -sfL https://renlm.github.io/sh/docker-save-images.sh | PLATFORM=linux/amd64 sh -s - -i moby/buildkit:buildx-stable-1 -i nginx:1.31.2-alpine -o tools
# $ curl -sfL https://renlm.github.io/sh/docker-save-images.sh | PLATFORM=linux/arm64 sh -s - -i moby/buildkit:buildx-stable-1 -i nginx:1.31.2-alpine -o tools
# $ curl -sfL https://renlm.github.io/sh/docker-save-images.sh | \
#     sh -s - \
#     --txt https://renlm.github.io/resources/cert-manager/v1.20.2/cert-manager-images.txt \
#     --txt https://renlm.github.io/resources/rancher/v2.14.2/rancher-images.txt \
#     --output rancher-images-v2.14.2
########################################################################
PLATFORM=${PLATFORM:-"linux/amd64,linux/arm64"}
OUTPUT=docker-save-images
IMAGES_ARR=""
TXT_ARR=""

# 颜色代码
_RED_='\033[0;31m'    # 红色
_GREEN_='\033[0;32m'  # 绿色
_YELLOW_='\033[0;33m' # 黄色
_NC_='\033[0m'        # 重置

# --- helper functions for logs ---
info()
{
  printf "[ ${_GREEN_}INFO${_NC_} ] $@\n"
}
warn()
{
  printf "[ ${_YELLOW_}WARN${_NC_} ] $@\n" >&2
}
fatal()
{
  printf "[ ${_RED_}ERROR${_NC_} ] $@\n" >&2
  exit 1
}

# --- download from url ---
download() {
  [ $# -eq 2 ] || fatal 'download needs exactly 2 arguments'

  # Disable exit-on-error so we can do custom error messages on failure
  set +e

  # Default to a failure status
  status=1

  case $DOWNLOADER in
    curl)
      printf "[ ${_GREEN_}下载${_NC_} ] curl -o $1 -sfL $2\n"
      curl -o $1 -sfL $2
      status=$?
    ;;
    wget)
      printf "[ ${_GREEN_}下载${_NC_} ] wget -qO $1 $2\n"
      wget -qO $1 $2
      status=$?
    ;;
    *)
      # Enable exit-on-error for fatal to execute
      set -e
      fatal "Incorrect executable '$DOWNLOADER'"
    ;;
  esac

  # Re-enable exit-on-error
  set -e

  # Abort if download command failed
  [ $status -eq 0 ] || fatal 'Download failed'
}

# 参数校验
if [ "$PLATFORM" = "linux/amd64" ] || [ "$PLATFORM" = "linux/arm64" ] || [ "$PLATFORM" = "linux/amd64,linux/arm64" ] || [ "$PLATFORM" = "linux/arm64,linux/amd64" ]; then
  info "PLATFORM: $PLATFORM"
else
  fatal "Unknown PLATFORM: $PLATFORM, linux/amd64 or linux/arm64 or linux/amd64,linux/arm64"
  exit 1
fi

help=false
usage () {
  info "USAGE: $0 [--txt rancher-images.txt] [--images registry:3.1.1] [--output rancher-images.tar]"
  info "  [-t|--txt url] txt file with list of images; one image per line."
  info "  [-i|--images image] docker image full name."
  info "  [-o|--output fileName] tar generated by docker save."
  info "  [-h|--help] Usage message"
}

while [ $# -gt 0 ]; do
  key="$1"
  case $key in
    -t|--txt)
    TXT_ARR="$TXT_ARR $2"
    shift # past argument
    shift # past value
    ;;
    -i|--images)
    IMAGES_ARR="$IMAGES_ARR $2"
    shift # past argument
    shift # past value
    ;;
    -o|--output)
    OUTPUT=$2
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    help=true
    shift
    ;;
    *)
    usage
    exit 1
    ;;
  esac
done

if $help; then
  usage
  exit 0
fi

# 下载镜像
DOWNLOADER=curl
DOWNLOADS_ROOT=/opt/${OUTPUT}
PLATFORM_NUM=$(( $(echo ${PLATFORM} | tr -cd ',' | wc -c) + 1 ))
if [ $PLATFORM_NUM -eq 1 ]; then
  DOWNLOADS_ROOT="/opt/${OUTPUT}-${PLATFORM##*/}"
fi
mkdir -p ${DOWNLOADS_ROOT}
DOWNLOADS_BASENAME=$(basename $DOWNLOADS_ROOT)
IMAGES_TXT=${DOWNLOADS_BASENAME}.txt
if [ ! -f ${DOWNLOADS_ROOT}/${IMAGES_TXT} ]; then
  echo "@PLATFORM=${PLATFORM}" > ${DOWNLOADS_ROOT}/${IMAGES_TXT}
fi
docker_pull() {
  pullImage="$@"
  if [ ! -z "${pullImage}" ]; then
    for i in $(seq 1 $PLATFORM_NUM); do
      targetImage="${pullImage}"
      PLATFORM_ITEM=$(echo "$PLATFORM" | cut -d ',' -f $i)
      if [ $PLATFORM_NUM -gt 1 ]; then
        targetImage="${targetImage}-${PLATFORM_ITEM##*/}"
      fi
      targetBasename=$(basename $targetImage)
      targetBasename=$(echo ${targetBasename} | sed "s/:/-/g")
      IMAGES_TXT_LINE="${pullImage}=${PLATFORM_ITEM}@${targetBasename}.tar@${targetImage}"
      IMAGES_TXT_LINE_NUM=$(cat ${DOWNLOADS_ROOT}/${IMAGES_TXT} | grep "${IMAGES_TXT_LINE}" | wc -l || true)
      if [ $IMAGES_TXT_LINE_NUM -eq 1 ]; then
        info "Image saved: ${targetImage}"
        continue
      fi
      if docker pull --platform ${PLATFORM_ITEM} ${pullImage} > /dev/null 2>&1; then
        if [ $PLATFORM_NUM -gt 1 ]; then
          if docker tag ${pullImage} ${targetImage} > /dev/null 2>&1; then
            info "Image saving: ${targetImage}"
            docker save --platform ${PLATFORM_ITEM} -o ${DOWNLOADS_ROOT}/${targetBasename}.tar ${targetImage}
            docker rmi ${targetImage} --force > /dev/null 2>&1 || true
            docker rmi ${pullImage} --force > /dev/null 2>&1 || true
            echo "${IMAGES_TXT_LINE}" >> ${DOWNLOADS_ROOT}/${IMAGES_TXT}
          else
            fatal "Image tag failed: ${targetImage}"
          fi
        else
          info "Image saving: ${targetImage}"
          docker save --platform ${PLATFORM_ITEM} -o ${DOWNLOADS_ROOT}/${targetBasename}.tar ${targetImage}
          docker rmi ${targetImage} --force > /dev/null 2>&1 || true
          echo "${IMAGES_TXT_LINE}" >> ${DOWNLOADS_ROOT}/${IMAGES_TXT}
        fi
      else
        fatal "Image pull failed: ${pullImage}"
      fi
    done
  fi
}
for image in $IMAGES_ARR; do
  docker_pull $image
done
for txt in $TXT_ARR; do
  txt_file=${txt##*/}
  download $txt_file $txt
  sed -i '/^#/d' $txt_file
  while IFS= read -r line; do
    docker_pull $line
  done < $txt_file
done

IMAGES_NUM=$(grep -v "^@PLATFORM=" ${DOWNLOADS_ROOT}/${IMAGES_TXT} | wc -l)
info "Creating ${DOWNLOADS_BASENAME}.tar.gz with $IMAGES_NUM images"
tar -czf ${DOWNLOADS_BASENAME}.tar.gz -C ${DOWNLOADS_ROOT%/*} ${DOWNLOADS_BASENAME}
