#!/bin/sh
set -e
set -o noglob
########################################################################
### 生成离线镜像包
# $ curl -sfL https://renlm.github.io/sh/docker-save-images.sh | \
#     PLATFORM=linux/amd64 sh -s - \
#     -t https://renlm.github.io/resources/cert-manager/v1.20.2/images.txt \
#     -t https://github.com/rancher/rancher/releases/download/v2.14.2/rancher-images.txt \
#     -i registry:3.1.1 \
#     -i nginx:1.31.2-alpine \
#     -o rancher-images-v2.14.2
########################################################################
IMAGES_TXT=images.txt
OUTPUT=save-images
IMAGES_ARR=""
TXT_ARR=""
PULLED=""
help=false
# linux/amd64
# linux/arm64
PLATFORM=${PLATFORM}
if [ "$PLATFORM" = "linux/amd64" ] || [ "$PLATFORM" = "linux/arm64" ]; then
  echo "PLATFORM: $PLATFORM"
else
  echo "Unknown PLATFORM: $PLATFORM, linux/amd64 or linux/arm64"
  exit 1
fi

usage () {
  echo "USAGE: $0 [--txt rancher-images.txt] [--images registry:3.1.1] [--output rancher-images.tar.gz]"
  echo "  [-t|--txt url] txt file with list of images; one image per line."
  echo "  [-i|--images image] docker image full name."
  echo "  [-o|--output fileName] tar.gz generated by docker save."
  echo "  [-h|--help] Usage message"
}

while [ $# -gt 0 ]; do
  key="$1"
  case $key in
    -t|--txt)
    TXT_ARR="$TXT_ARR $2"
    shift # past argument
    shift # past value
    ;;
    -i|--images)
    IMAGES_ARR="$IMAGES_ARR $2"
    shift # past argument
    shift # past value
    ;;
    -o|--output)
    OUTPUT=$2
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    help=true
    shift
    ;;
    *)
    usage
    exit 1
    ;;
  esac
done

if $help; then
  usage
  exit 0
fi

# 下载镜像
rm -fr ./${OUTPUT}
mkdir ${OUTPUT}
touch ${OUTPUT}/.${IMAGES_TXT}
docker_pull() {
  if [ ! -z "$@" ]; then
    echo "${@}" >> ${OUTPUT}/.${IMAGES_TXT}
    if docker pull --platform ${PLATFORM} "$@" > /dev/null 2>&1; then
      echo "Image pull success: $@"
      PULLED="${PULLED} $@"
    else
      if docker inspect "$@" > /dev/null 2>&1; then
        PULLED="${PULLED} $@"
      else
        echo "Image pull failed: $@"
      fi
    fi
  fi
}
for image in "${IMAGES_ARR}"; do
  docker_pull "$image"
done
for txt in "${TXT_ARR}"; do
  txt_file=${txt##*/}
  echo "curl -o $txt_file -sfL $txt"
  curl -o $txt_file -sfL $txt
  while IFS= read -r i; do
    docker_pull "$image"
  done < "${txt_file}"
done

echo "Creating ${OUTPUT}.tar.gz with $(echo ${PULLED} | wc -w | tr -d '[:space:]') images"
docker save $(echo ${PULLED}) | gzip --stdout > ${OUTPUT}.tar.gz
