apiVersion: v1
entries:
  core-service:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-01-07T09:37:17.701545838+08:00"
    dependencies:
    - name: templates
      repository: file://../../templates
      version: 0.0.1
    description: A Helm chart for core-service
    digest: 2fb049fec121074006bee95642c34551f3497b90cce96aa152b774a85d2962fc
    name: core-service
    type: application
    urls:
    - https://github.renlm.cn/helm/repo/core-service-0.0.1.tgz
    version: 0.0.1
  core-web:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-01-07T09:37:17.702204444+08:00"
    dependencies:
    - name: templates
      repository: file://../../templates
      version: 0.0.1
    description: A Helm chart for core-web
    digest: 67c26a1ba3137c5fea6c5cea543cad39901a8499797625226a85e2779c601ef2
    name: core-web
    type: application
    urls:
    - https://github.renlm.cn/helm/repo/core-web-0.0.1.tgz
    version: 0.0.1
generated: "2025-01-07T09:37:17.70071628+08:00"
